const app = require('./app/index')
const koaBody = require('koa-body')
const user = require('./routes/user')
const upload = require('./routes/upload')
const shopInfo = require('./routes/shopInfo')
const foodTypes = require('./routes/foodTypes')
const foodInfo = require('./routes/foodInfo')
const foodUnits = require('./routes/foodUnits')
const order = require('./routes/order')
const qr = require('./routes/qr')
const handError = require('./middleware/handlError')


app.use(koaBody())
app.use(handError)
app.use(user.routes())
app.use(upload.routes())
app.use(shopInfo.routes())
app.use(foodTypes.routes())
app.use(foodInfo.routes())
app.use(foodUnits.routes())
app.use(qr.routes())
app.use(order.routes())
app.listen(3000)